/**
 * Narrative — Chief agent reasoning narrative
 * Shows [AI] or [TEMPLATE] provenance badge
 */
export default function Narrative({ data, provenance }) {
  if (!data) return null

  const badge = data.provenance === 'AI' ? 'badge-ai'
    : data.provenance === 'TEMPLATE' ? 'badge-template'
    : 'badge-template'

  const badgeLabel = data.provenance === 'AI' ? 'AI NARRATIVE'
    : 'TEMPLATE'

  return (
    <div className="card">
      <div className="card-header">
        <span className="card-title">🧠 Chief Agent Reasoning</span>
        <span className={badge}>{badgeLabel}</span>
      </div>

      <div className="narrative-text">
        {data.narrative}
      </div>

      {data.llm_error && (
        <div style={{
          marginTop: '12px',
          padding: '8px 12px',
          background: 'var(--moderate-bg)',
          borderRadius: 'var(--radius-sm)',
          fontSize: '0.75rem',
          color: 'var(--moderate)',
        }}>
          Note: LLM narrative generation failed ({data.llm_error}). Using template fallback.
        </div>
      )}

      <div style={{
        marginTop: '16px',
        fontSize: '0.7rem',
        color: 'var(--text-muted)',
        display: 'flex',
        gap: '16px',
        flexWrap: 'wrap',
      }}>
        <span>Generated by: {data.generated_by}</span>
        {provenance && (
          <>
            <span>Scores: <span className="badge-rule" style={{ fontSize: '0.55rem' }}>RULE</span></span>
            <span>Narrative: <span className={badge} style={{ fontSize: '0.55rem' }}>{badgeLabel}</span></span>
          </>
        )}
      </div>
    </div>
  )
}
