"""
Sanjeevani v2 — Provenance Badge Utilities
Tags findings as [RULE] or [AI] for transparency.
"""


def tag_rule(finding: dict) -> dict:
    """Tag a finding with [RULE] provenance."""
    finding["provenance"] = "RULE"
    finding["provenance_tooltip"] = (
        f"Computed deterministically by clinical rule engine v{finding.get('rule_version', 'unknown')}"
    )
    return finding


def tag_ai(finding: dict) -> dict:
    """Tag a finding with [AI] provenance."""
    finding["provenance"] = "AI"
    finding["provenance_tooltip"] = (
        "Generated by AI and validated against rule engine outputs"
    )
    return finding


def tag_report(report: dict) -> dict:
    """Apply provenance badges to all sections of a report."""
    # Rule engine outputs get [RULE] badge
    for key in ["sofa", "qsofa", "sirs", "aki", "vwrs"]:
        if key in report.get("rule_facts", {}):
            data = report["rule_facts"][key]
            if isinstance(data, dict):
                tag_rule(data)

    for outlier in report.get("rule_facts", {}).get("outliers", []):
        if isinstance(outlier, dict):
            tag_rule(outlier)

    for amr in report.get("rule_facts", {}).get("amr", []):
        if isinstance(amr, dict):
            tag_rule(amr)

    # AI narrative gets [AI] badge
    if "ai_narrative" in report:
        report["ai_provenance"] = "AI"

    return report
